algoritmo "Função para imprimir um número n, n vezes"

// Função :

// Autor :

// Data : 6/6/2013

// Seção de Declarações 

var

n : inteiro



procedimento imprimeN(n:inteiro)

var

i : inteiro

j : inteiro



Inicio

para i de 1 ate n faca

     para j de 1 ate i faca

          escreva(i:3)

     fimpara

     escreval("")

fimpara

fimprocedimento



inicio

// Seção de Comandos 

escreval("Digite um numero qualquer")

leia(n)

imprimeN(n)

fimalgoritmo
