algoritmo "Maior numero"
// Função :
// Autor :
// Data : 06/05/2013
// Seção de Declarações 
var
	primeiroNum : real
	segundoNum : real

inicio
	// Seção de Comandos
	escreval ( "Entre com o primeiro numero:")
	leia (primeiroNum)
	escreval ("Entre com o segundo numero:")
	leia(segundoNum )
	se primeiroNum > segundoNum  entao
		escreval( "Maior numero é:" , primeiroNum)
	senao
		escreval("Maior numero é:" , segundoNum )   
	fimse 
fimalgoritmo
